---
title: "STA477_DataCleaning"
author: "Sakina Lord"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
```

```{r}
data_raw <- read.csv("T_F41SCHEDULE_P52.csv") %>% filter(YEAR > 2003) 
craft_type_lookup <- read.csv("craft_codes_lookup/T_AIRCRAFT_TYPES.csv")
```

```{r}
summary(data_raw)
```
```{r}
data_time <- data_raw %>% filter(YEAR > 2003) %>% mutate(time_pt = as.numeric(YEAR) + (as.numeric(QUARTER)) * 0.1)

data_joined <- left_join(data_time, craft_type_lookup, by = c("AIRCRAFT_TYPE" = "AC_TYPEID"))
```

```{r}
# Select only Boeing and Airbus for analysis
data.BA <- data_joined %>% filter(MANUFACTURER == "AIRBUS INDUSTRIE" | MANUFACTURER == "BOEING") %>%
  select("TOT_FLY_OPS", "TOT_DIR_MAINT", "TOTAL_AIR_HOURS", "AIRCRAFT_CONFIG", "UNIQUE_CARRIER_NAME","CARRIER_NAME", 
         "CARRIER", "REGION", "YEAR", "QUARTER", "time_pt",
         "AC_GROUP", "SSD_NAME", "MANUFACTURER", "LONG_NAME", "SHORT_NAME", "BEGIN_DATE")
colnames(data.BA)

#write.csv(data.BA, "lim_dataset.csv")


# Breif EDA
ggplot(data.BA, aes(x = TOTAL_AIR_HOURS)) + geom_col(aes(y = TOT_FLY_OPS))
```
```{r}
ggplot(data.BA, aes(x = TOTAL_AIR_HOURS)) + geom_line(aes(y = TOT_FLY_OPS))
```




```{r}
# ts
data.ts <- data_raw %>% filter(YEAR > 2003) %>%
  select(TOT_DIR_MAINT, AIRCRAFT_TYPE, UNIQUE_CARRIER_NAME) %>% na.omit()

data.ts <- ts(data.ts, start = 2004, freq = 4)
plot.ts(data.ts)
```

